### ISSUE TITLE
Page Path slash doesn't show in night mode

### ISSUE THREAD

**Issue by ericthelemur** [UWCS/uwcs-dextre#37]
![image](https://user-images.githubusercontent.com/8903016/164344786-8a61d261-ff88-4d59-ae4e-41eae04de144.png)

![image](https://user-images.githubusercontent.com/8903016/164344757-461e711c-f924-482a-a984-47afe7897e70.png)

On https://uwcs.co.uk/about/irc-guide/

**Comment by joshdavies14** [comment]
`lib/templates/lib/tags/breadcrumbs.html` is where this is, you'll probably want to change line 4 to detect if night mode is set and change the `has-background-light-scheme` class accordingly :)
