### ISSUE TITLE
Navbar dropdown not working on mobile

### ISSUE THREAD

**Issue by the-Bruce** [UWCS/uwcs-dextre#4]
Default Bulma provides no way for mobile devices to trigger :hover effects. This was fixed for most things in https://github.com/UWCS/uwcs-dextre/blob/df57acee7fc79a3517b102c148c077fc31d04877/static/js/core.js but navbar dropdown were missed. This makes accessing profile and logout options hard as the user dropdown doesn't trigger.

**Steps to reproduce**: open website on touchscreen device that doesn't emulate :hover (e.g. iOS/Android) while logged in. Click username in navbar.
*Expected behaviour*: menu should appear to display logout and profile options.
*Observed behaviour*: nothing happens
*Tested on*: iPad Air (3rd generation) running iOS 14.5

**Comment by joshdavies14** [comment]
Thanks for reporting! I've fixed this locally, and once my exam tomorrow is out of the way I'm hoping to deploy the fix this week. :)
